### ISSUE TITLE
Error when I try to add user

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1355]
When I buildout SPD and I try to register or when I try to run the import_users script I get the same error: AttributeError: 'Pool' object has no attribute 'name'

Some more information is there when I run the script: 

```
Traceback (most recent call last):
  File "bin/import_users", line 112, in <module>
    sys.exit(adhocracy_core.scripts.import_users.import_users())
  File "/home/magda/Documents/dev/adhocracy3/src/adhocracy_core/adhocracy_core/scripts/import_users.py", line 43, in import_users
    _import_users(env['root'], env['registry'], args.filename)
  File "/home/magda/Documents/dev/adhocracy3/src/adhocracy_core/adhocracy_core/scripts/import_users.py", line 54, in _import_users
    user = locator.get_user_by_login(user_info['name'])
  File "/home/magda/Documents/dev/adhocracy3/src/adhocracy_core/adhocracy_core/resources/principal.py", line 260, in get_user_by_login
    if user.name == login:
AttributeError: 'Pool' object has no attribute 'name'
```

**Comment by joka** [comment]
Should be fixed now in master

**Comment by joka** [comment]
This is a bug since we implementd user badges. don't know why  all tests passed

**Comment by joka** [comment]
All test pass in the backend, so i close this now
