### ISSUE TITLE
TypeError while running sd_evolve --latest

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3.mercator#1673]
Hi,

while updating from 0.2.0 to 0.3.8 on the spd process I received the following error:

```
root@spd-adhocracy3-stage-guest38:/home/adhocracy3/adhocracy3# bin/sd_evolve --latest etc/backend.ini
2015-09-24 07:12:35,958 INFO  [ZEO.ClientStorage][MainThread] ('localhost', 8001) ClientStorage (pid=23485) created RW/normal for storage: 'main'
2015-09-24 07:12:35,958 INFO  [ZEO.cache][MainThread] created temporary cache file 5
2015-09-24 07:12:35,961 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8001))])] ('localhost', 8001) Testing connection <ManagedClientConnection ('127.0.0.1', 8001)>
2015-09-24 07:12:35,961 INFO  [ZEO.zrpc.Connection(b'C')][('localhost', 8001) zeo client networking thread] (127.0.0.1:8001) received handshake b'Z3101'
2015-09-24 07:12:36,062 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8001))])] ('localhost', 8001) Server authentication protocol None
2015-09-24 07:12:36,062 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8001))])] ('localhost', 8001) Connected to storage: ('localhost', 8001)
2015-09-24 07:12:36,063 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8001))])] ('localhost', 8001) No verification necessary -- empty cache
2015-09-24 07:12:36,071 INFO  [ZEO.ClientStorage][MainThread] ('localhost', 8002) ClientStorage (pid=23485) created RW/normal for storage: 'main'
2015-09-24 07:12:36,072 INFO  [ZEO.cache][MainThread] created temporary cache file 10
2015-09-24 07:12:36,073 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8002))])] ('localhost', 8002) Testing connection <ManagedClientConnection ('127.0.0.1', 8002)>
2015-09-24 07:12:36,073 INFO  [ZEO.zrpc.Connection(b'C')][('localhost', 8002) zeo client networking thread] (127.0.0.1:8002) received handshake b'Z3101'
2015-09-24 07:12:36,174 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8002))])] ('localhost', 8002) Server authentication protocol None
2015-09-24 07:12:36,175 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8002))])] ('localhost', 8002) Connected to storage: ('localhost', 8002)
2015-09-24 07:12:36,176 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 8002))])] ('localhost', 8002) No verification necessary -- empty cache
/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/multipledispatch/dispatcher.py:24: AmbiguityWarning: 
Ambiguities exist in dispatched function create_arbitrary_filter_node

The following signatures may result in ambiguous behavior:
	[object, int, str], [ReferenceIndex, object, str]
	[object, bool, str], [ReferenceIndex, object, str]
	[object, str, str], [ReferenceIndex, object, str]
	[object, datetime, str], [ReferenceIndex, object, str]


Consider making the following additions:

@dispatch(ReferenceIndex, int, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, bool, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, str, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, datetime, str)
def create_arbitrary_filter_node(...)
  warn(warning_text(dispatcher.name, ambiguities), AmbiguityWarning)
2015-09-24 07:12:36,575 WARNI [substanced.catalog.subscribers][MainThread] Cannot autosync/autoreindex catalog due to unfinished evolve steps
Executing evolution step adhocracy_core.evolution.add_workflow_assignment_sheet_to_pools_simples
2015-09-24 07:12:36,578 INFO  [adhocracy_core.evolution][MainThread] Running evolve step: Add generic workflow sheet to pools and simples.
2015-09-24 07:12:36,578 INFO  [adhocracy_core.evolution][MainThread] Running evolve step: Add generic workflow sheet to pools and simples.
2015-09-24 07:12:36,587 ERROR [ZODB.Connection][MainThread] Couldn't load state for BTrees.OOBTree.OOBTree 0x0125
Traceback (most recent call last):
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/ZODB/Connection.py", line 871, in setstate
    self._setstate(obj)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/ZODB/Connection.py", line 925, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/ZODB/serialize.py", line 635, in setGhostState
    obj.__setstate__(state)
TypeError: Object has default comparison
Traceback (most recent call last):
  File "bin/sd_evolve", line 11, in <module>
    sys.exit(main())
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/scripts/evolve.py", line 83, in main
    complete = manager.evolve(latest)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/evolution/__init__.py", line 75, in evolve
    func(self.context)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/evolution/__init__.py", line 119, in logger_decorator
    func(*args, **kwargs)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/evolution/__init__.py", line 293, in add_workflow_assignment_sheet_to_pools_simples
    migrate_new_sheet(root, IPool, IWorkflowAssignment)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/evolution/__init__.py", line 62, in migrate_new_sheet
    resources = catalogs.search(query).elements
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/catalog/__init__.py", line 51, in search
    elements = self._search_elements(query)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/catalog/__init__.py", line 101, in _search_elements
    elements = index_query.execute(resolver=None)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/hypatia/query/__init__.py", line 110, in execute
    resolver=resolver
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/catalog/indexes.py", line 65, in resultset_from_query
    docids = query._apply(names)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/hypatia/query/__init__.py", line 268, in _apply
    return self.index.applyAll(self._get_value(names))
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/hypatia/keyword/__init__.py", line 110, in applyAll
    return self.apply({'query': values, 'operator': 'and'})
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/hypatia/keyword/__init__.py", line 284, in apply
    return self.search(query, operator=operator)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/hypatia/keyword/__init__.py", line 255, in search
    docids = self._fwd_index.get(word, self.family.IF.Set())
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/ZODB/Connection.py", line 871, in setstate
    self._setstate(obj)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/ZODB/Connection.py", line 925, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/ZODB/serialize.py", line 635, in setGhostState
    obj.__setstate__(state)
TypeError: Object has default comparison
```

**Comment by joka** [comment]
I guess we did not expect such an old installation and removed an outdated interfaces/class that is missing now. 
Where is the staging installation to test this?

**Comment by slomo** [comment]
It is on benhabib (spd-stage)

**Comment by joka** [comment]
@pallix we removed adhocracy_core.workflow.ISample without adding a migration.

**Comment by pallix** [comment]
Can we ensure such errors do not occur by checking the interfaces in the db against the one from the code? or at least detect them earlier by testing the migration continously?
