### ISSUE TITLE
Storing Blobs in ZODB does not work in test environment.

### ISSUE THREAD

**Issue by mkind** [liqd/adhocracy3.mercator#464]
At the moment, it is not possible to submit proposals, respectively images. I falsely reported this in the old [server responds 500 issue](https://github.com/liqd/adhocracy3/issues/370#issuecomment-69201981). The log says:

    2015-01-08 16:48:19,546 ERROR [adhocracy_core.rest.exceptions][MainThread] internal
    Traceback (most recent call last):
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.1-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
        response = handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_exclog-0.7-py3.4.egg/pyramid_exclog/__init__.py", line 115, in exclog_tween
        _handle_error(request, getLogger, get_message)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_exclog-0.7-py3.4.egg/pyramid_exclog/__init__.py", line 111, in exclog_tween
        return handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 82, in tm_tween
        reraise(*exc_info)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.7-py3.4.egg/pyramid_tm/compat.py", line 13, in reraise
        raise value
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 70, in tm_tween
        manager.commit()
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_manager.py", line 111, in commit
        return self.get().commit()
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 280, in commit
        reraise(t, v, tb)
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_compat.py", line 55, in reraise
        raise value
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 271, in commit
        self._commitResources()
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 417, in _commitResources
        reraise(t, v, tb)
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_compat.py", line 55, in reraise
        raise value
      File "/home/mkind/code/adhocracy3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 391, in _commitResources
        rm.commit(self)
      File "/home/mkind/code/adhocracy3/eggs/ZODB-4.0.1-py3.4.egg/ZODB/Connection.py", line 575, in commit
        self._commit(transaction)
      File "/home/mkind/code/adhocracy3/eggs/ZODB-4.0.1-py3.4.egg/ZODB/Connection.py", line 631, in _commit
        self._store_objects(ObjectWriter(obj), transaction)
      File "/home/mkind/code/adhocracy3/eggs/ZODB-4.0.1-py3.4.egg/ZODB/Connection.py", line 674, in _store_objects
        repr(self._storage))
    ZODB.POSException.Unsupported: Storing Blobs in <ZODB.MappingStorage.MappingStorage object at 0x7f80ba0e6ba8> is not supported.

**Comment by ChristianSi** [comment]
I'll put this on hold for now since it's unclear what, if anything, could be done in the backend.

**Comment by nidico** [comment]
This is obsolete since #655, since we now use a real database (by means of `etc/test_with_ws.ini`) in the respective acceptance tests.
