### ISSUE TITLE
Duplicate tpc_begin calls for same transaction

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#583]
When running `bin/py.test src/adhocracy_frontend/adhocracy_frontend/tests/acceptance/test_user_login.py` I have the following error in the backend log on the first test (`test_register`):

```
2015-01-26 19:04:38,167 ERROR [adhocracy_core.rest.exceptions][MainThread] internal
Traceback (most recent call last):
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.1-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tobib/a3/a3/eggs/pyramid_exclog-0.7-py3.4.egg/pyramid_exclog/__init__.py", line 115, in exclog_tween
    _handle_error(request, getLogger, get_message)
  File "/home/tobib/a3/a3/eggs/pyramid_exclog-0.7-py3.4.egg/pyramid_exclog/__init__.py", line 111, in exclog_tween
    return handler(request)
  File "/home/tobib/a3/a3/eggs/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/home/tobib/a3/a3/eggs/pyramid_tm-0.7-py3.4.egg/pyramid_tm/compat.py", line 13, in reraise
    raise value
  File "/home/tobib/a3/a3/eggs/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 70, in tm_tween
    manager.commit()
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_compat.py", line 55, in reraise
    raise value
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_compat.py", line 55, in reraise
    raise value
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 389, in _commitResources
    rm.tpc_begin(self)
  File "/home/tobib/a3/a3/eggs/ZODB-4.0.1-py3.4.egg/ZODB/Connection.py", line 559, in tpc_begin
    self._normal_storage.tpc_begin(transaction)
  File "/home/tobib/a3/a3/eggs/ZODB-4.0.1-py3.4.egg/ZODB/utils.py", line 293, in __call__
    return func(*args, **kw)
  File "/home/tobib/a3/a3/eggs/ZODB-4.0.1-py3.4.egg/ZODB/MappingStorage.py", line 280, in tpc_begin
    "Duplicate tpc_begin calls for same transaction")
ZODB.POSException.StorageTransactionError: Duplicate tpc_begin calls for same transaction
```

This does not happen in my development setup, only in the test. I bisected the issue and found that it exists since ea467f3049744de457c9bfd9b9362a5f81507a8c.

**Comment by nidico** [comment]
Is this related to #451?

**Comment by nidico** [comment]
This also occurs (at least to me, but not to @MagdaN) in the protractor acceptance tests, despite them using `etc/test_with_ws.ini`, i.e. a real, non-memory-only, database.

**Comment by nidico** [comment]
This does not seem to happen anymore, closing.

**Comment by pallix** [comment]
I think I had the same error when sending emails for bplaene. I will open a another ticket if I see the error again.
