### ISSUE TITLE
OSError: image file is truncated (32 bytes not processed)

### ISSUE THREAD

**Issue by mkind** [liqd/adhocracy3.mercator#604]
In the *productive* environment I created a proposal using one of the [example](https://github.com/liqd/adhocracy3/blob/master/docs/source/_static/python.jpg) [pictures](https://github.com/liqd/adhocracy3/blob/master/docs/source/_static/python2.jpg). Sometimes there is no proposal pic shown in the proposal list. Requesting `http://localhost:6541/mercator/assets/0000001//thumbnail` results in the following error message in the backend log:

    2015-01-28 18:16:13,247 ERROR [adhocracy_core.rest.exceptions][MainThread] internal
    Traceback (most recent call last):
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
        response = handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_exclog-0.7-   py3.4.egg/pyramid_exclog/__init__.py", line 115, in exclog_tween
        _handle_error(request, getLogger, get_message)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_exclog-0.7-py3.4.egg/pyramid_exclog/__init__.py", line 111, in exclog_tween
        return handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.10-py3.4.egg/pyramid_tm/__init__.py", line 95, in tm_tween
        reraise(*exc_info)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.10-py3.4.egg/pyramid_tm/compat.py", line 15, in reraise
        raise value
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.10-py3.4.egg/pyramid_tm/__init__.py", line 76, in tm_tween
        response = handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 163, in handle_request
        response = view_callable(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 329, in attr_view
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line    305, in predicate_wrapper
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 245, in _secured_view
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 218, in wrapper
        response = view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 355, in rendered_view
        result = view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 491, in _class_view
        response = getattr(inst, attr)()
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/rest/views.py", line 669, in get
        return file.get_response(self.context, self.request.registry)
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/asset.py", line    126, in get_response
        file = self._crop_and_resize_image(context, registry)
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/asset.py", line 140, in _crop_and_resize_image
        cropped_image = self._crop_if_needed(image)
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/asset.py", line   182, in _crop_if_needed
        return image.crop(crop_box)
      File "/home/mkind/code/adhocracy3/eggs/Pillow-2.7.0-py3.4-linux-x86_64.egg/PIL/Image.py", line 1012, in crop
        self.load()
      File "/home/mkind/code/adhocracy3/eggs/Pillow-2.7.0-py3.4-linux-x86_64.egg/PIL/ImageFile.py",    line 229, in load
        "(%d bytes not processed)" % len(b))
    OSError: image file is truncated (32 bytes not processed)

**Comment by ChristianSi** [comment]
How can I reproduce this problem? I created a few proposals but it never happened.

**Comment by mkind** [comment]
Well, the issue did not occur on uploading any images. Creating proposals worked fine for me. The problem arised during loading the proposal list with its thumbnails or while loading the proposal detail view. I'll check whether the current build makes it reproducable.

**Comment by mkind** [comment]
Seems to be fixed so far. I am not able to reproduce the issue.
