### ISSUE TITLE
ValueError and TransientError while parsing depth parameter

### ISSUE THREAD

**Issue by mkind** [liqd/adhocracy3.mercator#671]
Providing a float value as `depth` parameter results in 

    Traceback (most recent call last):
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/__init__.py", line 53, in get
        appstruct.update(self._get_reference_appstruct(params))
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/pool.py", line 50, in _get_reference_appstruct
        depth = self._build_depth(params)
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/pool.py", line 100, in _build_depth
        return None if raw_depth == 'all' else int(raw_depth)
    ValueError: invalid literal for int() with base 10: '1.4'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/mkind/code/adhocracy3/eggs/pyramid_exclog-0.7-py3.4.egg/pyramid_exclog/__init__.py", line 111, in exclog_tween
        return handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.11-py3.4.egg/pyramid_tm/__init__.py", line 94, in tm_tween
        reraise(*exc_info)
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.11-py3.4.egg/pyramid_tm/compat.py", line 15, in reraise
        raise value
      File "/home/mkind/code/adhocracy3/eggs/pyramid_tm-0.11-py3.4.egg/pyramid_tm/__init__.py", line 75, in tm_tween
        response = handler(request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 163, in handle_request
        response = view_callable(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 596, in __call__
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 329, in attr_view
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 305, in predicate_wrapper
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 245, in _secured_view
        return view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 355, in rendered_view
        result = view(context, request)
      File "/home/mkind/code/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 491, in _class_view
         response = getattr(inst, attr)()
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/rest/views.py", line 498, in   get
        return super().get()
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/rest/views.py", line 411, in get
        cstruct['data'] = self._get_sheets_data_cstruct()
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/rest/views.py", line 423, in   _get_sheets_data_cstruct
        appstruct = sheet.get(params=queryparams)
      File "/home/mkind/code/adhocracy3/src/adhocracy_core/adhocracy_core/sheets/__init__.py", line 64, in get
        raise TransientError(str(err))
    transaction.interfaces.TransientError: invalid literal for int() with base 10: '1.4'

Example request:
`GET http://localhost:6541/mercator?content_type=adhocracy_mercator.resources.mercator.IMercatorProposalVersion&depth=1.4 HTTP/1.1` , which results in `HTTP/1.1 500 Internal Server Error` .

**Comment by ChristianSi** [comment]
That should result in status code 400 Bad Request rather than 500. I'll take a look.

**Comment by ChristianSi** [comment]
There was a little bug in the validation logic, and I also found the same problem in another validator. Nice catch!

I'll push a fix.
